$(document).ready(function(){
$("#but-lang").click(function(){
$("#Languages").show();
$("#Frameworks").hide();
$("#Other").hide();
$("#Databases").hide();
});
$("#but-frame").click(function(){
$("#Languages").hide();
$("#Frameworks").show();
$("#Other").hide();
$("#Databases").hide();
});
$("#but-db").click(function(){
$("#Languages").hide();
$("#Frameworks").hide();
$("#Other").hide();
$("#Databases").show();
});
$("#but-oth").click(function(){
$("#Languages").hide();
$("#Frameworks").hide();
$("#Other").show();
$("#Databases").hide();
});
});
